### PR TITLE
First state reached - open for discussion.

### PR DESCRIPTION
**Pull request by 0815fox**
(For reference, see original discussion https://github.com/goenning/typed-pg/issues/7#issuecomment-229786459)

pg-pool was seperated from node-postgres by the author.
This typing is based on version 6.x.

The definition of the interface client is a copy&paste from https://github.com/goenning/typed-pg with some modifications. I hope I did not overlook sth. important. Finally the definition of client should be used in both, pg and pg-pool, but due to circular dependencies between both modules it is duplicated in here.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Could you `.gitignore` the `typings/` directory? Aside from that, looks great 😄

**Comment by 0815fox** [comment]
Ouch,thought I did it...

**Comment by goenning** [comment]
Awesome. I'll look into adding this as a dependency to `pg`.

**Comment by 0815fox** [comment]
Great. Do you need help with pg itself? Else I could do that too (as exercise) Do you want to move it to typed-typings before?

**Comment by goenning** [comment]
Sure, you're welcome! I've just moved it 👍

**Pull request merged**
